"""Comprehensive honeypot-relevant CVE catalog — seeded and expandable by operators."""

from __future__ import annotations

from typing import Any

# category keys: web_rce, cms, network, remote_access, database, cloud, iot, proxy, mail, container, auth_bypass

def _c(
    cve_id: str,
    summary: str,
    *,
    severity: str = "high",
    cvss: float | None = None,
    category: str = "web_rce",
    vendor: str | None = None,
    product: str | None = None,
    tags: list[str] | None = None,
    detection_hint: str | None = None,
) -> dict[str, Any]:
    return {
        "cve_id": cve_id,
        "summary": summary,
        "severity": severity,
        "cvss_score": cvss,
        "category": category,
        "vendor": vendor,
        "product": product,
        "tags": tags or [],
        "detection_hint": detection_hint,
        "references": [f"https://nvd.nist.gov/vuln/detail/{cve_id}"],
    }


CVE_CATALOG: list[dict[str, Any]] = [
    # --- Critical web / framework RCE ---
    _c("CVE-2021-44228", "Apache Log4j2 JNDI RCE (Log4Shell).", severity="critical", cvss=10.0, vendor="Apache", product="Log4j", tags=["log4shell", "jndi"], detection_hint="${jndi:ldap://"),
    _c("CVE-2021-45046", "Log4j incomplete fix; additional JNDI RCE vectors.", severity="critical", cvss=9.0, vendor="Apache", product="Log4j", tags=["log4shell"]),
    _c("CVE-2021-45105", "Log4j DoS via crafted recursive lookups.", severity="high", cvss=7.5, vendor="Apache", product="Log4j"),
    _c("CVE-2022-22965", "Spring Framework RCE (Spring4Shell) on JDK 9+.", severity="critical", cvss=9.8, vendor="VMware", product="Spring Framework", tags=["spring4shell"], detection_hint="class.module.classLoader"),
    _c("CVE-2022-22963", "Spring Cloud Function SpEL RCE.", severity="critical", cvss=9.8, vendor="VMware", product="Spring Cloud Function"),
    _c("CVE-2023-22515", "Atlassian Confluence unauthenticated admin access.", severity="critical", cvss=10.0, category="cms", vendor="Atlassian", product="Confluence", tags=["confluence"]),
    _c("CVE-2023-22527", "Confluence template injection RCE.", severity="critical", cvss=10.0, category="cms", vendor="Atlassian", product="Confluence"),
    _c("CVE-2022-26134", "Confluence OGNL injection RCE.", severity="critical", cvss=9.8, category="cms", vendor="Atlassian", product="Confluence"),
    _c("CVE-2021-26084", "Confluence OGNL injection RCE.", severity="critical", cvss=9.8, category="cms", vendor="Atlassian", product="Confluence"),
    _c("CVE-2019-19781", "Citrix ADC/Gateway path traversal RCE.", severity="critical", cvss=9.8, category="proxy", vendor="Citrix", product="ADC"),
    _c("CVE-2023-4966", "Citrix Bleed — session token leak in NetScaler.", severity="critical", cvss=9.4, category="proxy", vendor="Citrix", product="NetScaler"),
    _c("CVE-2023-34362", "Progress MOVEit Transfer SQLi → RCE.", severity="critical", cvss=9.8, category="file_transfer", vendor="Progress", product="MOVEit"),
    _c("CVE-2021-26855", "Microsoft Exchange SSRF (ProxyLogon).", severity="critical", cvss=9.8, category="mail", vendor="Microsoft", product="Exchange"),
    _c("CVE-2021-26857", "Microsoft Exchange unsafe deserialization RCE.", severity="critical", cvss=9.8, category="mail", vendor="Microsoft", product="Exchange"),
    _c("CVE-2021-26858", "Microsoft Exchange post-auth file write.", severity="high", cvss=8.8, category="mail", vendor="Microsoft", product="Exchange"),
    _c("CVE-2021-27065", "Microsoft Exchange post-auth file write.", severity="high", cvss=8.8, category="mail", vendor="Microsoft", product="Exchange"),
    _c("CVE-2020-0688", "Exchange control panel deserialization RCE.", severity="high", cvss=8.8, category="mail", vendor="Microsoft", product="Exchange"),
    _c("CVE-2017-0144", "SMBv1 RCE EternalBlue (MS17-010).", severity="critical", cvss=8.1, category="network", vendor="Microsoft", product="SMBv1", tags=["eternalblue"]),
    _c("CVE-2017-0143", "SMBv1 remote code execution.", severity="critical", cvss=8.5, category="network", vendor="Microsoft", product="SMBv1"),
    _c("CVE-2019-0708", "RDP BlueKeep pre-auth RCE.", severity="critical", cvss=9.8, category="remote_access", vendor="Microsoft", product="RDP", tags=["bluekeep"]),
    _c("CVE-2014-6271", "GNU Bash Shellshock env injection.", severity="critical", cvss=9.8, category="network", vendor="GNU", product="Bash", tags=["shellshock"]),
    _c("CVE-2014-6278", "GNU Bash Shellshock variant.", severity="critical", cvss=9.8, category="network", vendor="GNU", product="Bash"),
    # --- CMS / PHP ---
    _c("CVE-2023-6553", "WordPress Backup Migration RCE.", severity="critical", cvss=9.8, category="cms", vendor="WordPress", product="Backup Migration"),
    _c("CVE-2023-28121", "WooCommerce unauthorized admin (critical chain).", severity="critical", cvss=9.8, category="cms", vendor="WooCommerce", product="WordPress plugin"),
    _c("CVE-2022-21661", "WordPress SQL injection.", severity="high", cvss=8.8, category="cms", vendor="WordPress", product="Core"),
    _c("CVE-2019-8943", "WordPress crop-image RCE chain.", severity="high", cvss=8.8, category="cms", vendor="WordPress", product="Core"),
    _c("CVE-2018-7600", "Drupalgeddon2 — Drupal core RCE.", severity="critical", cvss=9.8, category="cms", vendor="Drupal", product="Core", tags=["drupalgeddon"]),
    _c("CVE-2018-7602", "Drupal core RCE (authenticated).", severity="high", cvss=8.1, category="cms", vendor="Drupal", product="Core"),
    _c("CVE-2019-6340", "Drupal REST module RCE.", severity="high", cvss=8.1, category="cms", vendor="Drupal", product="REST"),
    _c("CVE-2021-41773", "Apache HTTP Server 2.4.49 path traversal.", severity="high", cvss=7.5, vendor="Apache", product="httpd", detection_hint="/cgi-bin/"),
    _c("CVE-2021-42013", "Apache HTTP Server 2.4.50 path traversal bypass.", severity="critical", cvss=9.8, vendor="Apache", product="httpd"),
    _c("CVE-2019-0211", "Apache HTTP local privilege escalation.", severity="high", cvss=7.8, vendor="Apache", product="httpd"),
    _c("CVE-2023-50164", "Apache Struts file upload RCE.", severity="critical", cvss=9.8, vendor="Apache", product="Struts"),
    _c("CVE-2017-5638", "Apache Struts Jakarta multipart RCE.", severity="critical", cvss=10.0, vendor="Apache", product="Struts", tags=["equifax"]),
    _c("CVE-2017-12611", "Apache Struts OGNL RCE.", severity="critical", cvss=9.8, vendor="Apache", product="Struts"),
    # --- VPN / edge ---
    _c("CVE-2024-3400", "Palo Alto PAN-OS GlobalProtect command injection.", severity="critical", cvss=10.0, category="proxy", vendor="Palo Alto", product="PAN-OS"),
    _c("CVE-2023-27997", "FortiOS SSL-VPN heap overflow RCE.", severity="critical", cvss=9.2, category="proxy", vendor="Fortinet", product="FortiOS"),
    _c("CVE-2022-40684", "FortiOS/FortiProxy auth bypass.", severity="critical", cvss=9.8, category="auth_bypass", vendor="Fortinet", product="FortiOS"),
    _c("CVE-2023-0669", "Fortra GoAnywhere MFT pre-auth RCE.", severity="critical", cvss=9.8, category="file_transfer", vendor="Fortra", product="GoAnywhere"),
    _c("CVE-2021-22893", "Ivanti Pulse Connect Secure RCE.", severity="critical", cvss=9.8, category="proxy", vendor="Ivanti", product="Pulse Secure"),
    _c("CVE-2023-46805", "Ivanti Connect Secure auth bypass.", severity="critical", cvss=9.8, category="auth_bypass", vendor="Ivanti", product="Connect Secure"),
    _c("CVE-2024-21887", "Ivanti Connect Secure command injection.", severity="critical", cvss=9.8, category="proxy", vendor="Ivanti", product="Connect Secure"),
    _c("CVE-2020-5902", "F5 BIG-IP TMUI RCE.", severity="critical", cvss=9.8, category="proxy", vendor="F5", product="BIG-IP"),
    _c("CVE-2022-1388", "F5 BIG-IP iControl REST auth bypass RCE.", severity="critical", cvss=9.8, category="proxy", vendor="F5", product="BIG-IP"),
    # --- Database ---
    _c("CVE-2012-2122", "MySQL auth bypass (memcmp).", severity="high", cvss=7.5, category="database", vendor="Oracle", product="MySQL"),
    _c("CVE-2020-1472", "Netlogon Zerologon elevation of privilege.", severity="critical", cvss=10.0, category="network", vendor="Microsoft", product="Netlogon", tags=["zerologon"]),
    _c("CVE-2019-9193", "PostgreSQL COPY FROM PROGRAM RCE.", severity="high", cvss=8.8, category="database", vendor="PostgreSQL", product="Core"),
    _c("CVE-2021-22946", "curl TELNET stack buffer overflow.", severity="high", cvss=7.5, category="network", vendor="curl", product="libcurl"),
    _c("CVE-2022-0847", "Linux kernel Dirty Pipe local privilege escalation.", severity="high", cvss=7.8, category="network", vendor="Linux", product="Kernel", tags=["dirtypipe"]),
    # --- IoT / botnet ---
    _c("CVE-2016-10401", "Netgear WNR2000v5 auth bypass.", severity="critical", cvss=9.8, category="iot", vendor="Netgear", product="Router"),
    _c("CVE-2017-17215", "Huawei HG532 remote code execution (Mirai vector).", severity="critical", cvss=9.8, category="iot", vendor="Huawei", product="HG532", tags=["mirai"]),
    _c("CVE-2018-10562", "Dasan GPON router command injection.", severity="critical", cvss=9.8, category="iot", vendor="Dasan", product="GPON"),
    _c("CVE-2019-15107", "Webmin password_change.cgi RCE.", severity="critical", cvss=9.8, category="web_rce", vendor="Webmin", product="Webmin"),
    _c("CVE-2019-18935", "Telerik UI .NET deserialization RCE.", severity="critical", cvss=9.8, category="web_rce", vendor="Progress", product="Telerik UI"),
    _c("CVE-2020-10148", "SolarWinds Orion API auth bypass RCE.", severity="critical", cvss=9.8, category="web_rce", vendor="SolarWinds", product="Orion"),
    _c("CVE-2021-21972", "VMware vCenter Server RCE.", severity="critical", cvss=9.8, category="cloud", vendor="VMware", product="vCenter"),
    _c("CVE-2021-22005", "VMware vCenter analytics file upload RCE.", severity="critical", cvss=9.8, category="cloud", vendor="VMware", product="vCenter"),
    _c("CVE-2021-22205", "GitLab ExifTool RCE.", severity="critical", cvss=10.0, category="web_rce", vendor="GitLab", product="GitLab"),
    _c("CVE-2023-7028", "GitLab account takeover via password reset.", severity="high", cvss=8.7, category="auth_bypass", vendor="GitLab", product="GitLab"),
    # --- Container / cloud ---
    _c("CVE-2019-5736", "runc container escape.", severity="high", cvss=8.6, category="container", vendor="Docker", product="runc"),
    _c("CVE-2020-15257", "containerd-shim API access container escape.", severity="high", cvss=8.8, category="container", vendor="containerd", product="shim"),
    _c("CVE-2024-3094", "XZ Utils backdoor (liblzma).", severity="critical", cvss=10.0, category="network", vendor="XZ", product="liblzma", tags=["supply_chain"]),
    _c("CVE-2023-48788", "FortiClient EMS SQL injection RCE.", severity="critical", cvss=9.8, category="proxy", vendor="Fortinet", product="FortiClient EMS"),
    # --- SSH / Telnet / remote ---
    _c("CVE-2018-15473", "OpenSSH username enumeration.", severity="medium", cvss=5.3, category="remote_access", vendor="OpenSSH", product="OpenSSH"),
    _c("CVE-2023-38408", "OpenSSH PKCS#11 remote code execution (specific configs).", severity="high", cvss=9.8, category="remote_access", vendor="OpenSSH", product="OpenSSH"),
    _c("CVE-2016-6662", "MySQL/MariaDB root privilege escalation.", severity="high", cvss=8.8, category="database", vendor="MySQL", product="MySQL"),
    _c("CVE-2020-1350", "Windows DNS SIG RR heap overflow (SigRed).", severity="critical", cvss=10.0, category="network", vendor="Microsoft", product="DNS Server"),
    _c("CVE-2023-23397", "Microsoft Outlook elevation of privilege (NTLM leak).", severity="critical", cvss=9.8, category="mail", vendor="Microsoft", product="Outlook"),
    _c("CVE-2022-41040", "Microsoft Exchange SSRF (ProxyNotShell).", severity="high", cvss=8.8, category="mail", vendor="Microsoft", product="Exchange"),
    _c("CVE-2022-41082", "Microsoft Exchange RCE chain (ProxyNotShell).", severity="high", cvss=8.0, category="mail", vendor="Microsoft", product="Exchange"),
    # --- Additional web app surface ---
    _c("CVE-2020-14882", "Oracle WebLogic IIOP/T3 RCE.", severity="critical", cvss=9.8, category="web_rce", vendor="Oracle", product="WebLogic"),
    _c("CVE-2020-14883", "Oracle WebLogic console RCE.", severity="critical", cvss=9.8, category="web_rce", vendor="Oracle", product="WebLogic"),
    _c("CVE-2017-10271", "Oracle WebLogic WLS-WSAT RCE.", severity="critical", cvss=9.8, category="web_rce", vendor="Oracle", product="WebLogic"),
    _c("CVE-2019-2725", "Oracle WebLogic async response RCE.", severity="critical", cvss=9.8, category="web_rce", vendor="Oracle", product="WebLogic"),
    _c("CVE-2022-26138", "Atlassian Questions for Confluence hardcoded creds.", severity="critical", cvss=9.8, category="auth_bypass", vendor="Atlassian", product="Confluence"),
    _c("CVE-2023-29357", "Microsoft SharePoint auth bypass.", severity="critical", cvss=9.8, category="cms", vendor="Microsoft", product="SharePoint"),
    _c("CVE-2019-0604", "Microsoft SharePoint RCE.", severity="critical", cvss=9.8, category="cms", vendor="Microsoft", product="SharePoint"),
    _c("CVE-2020-14179", "Jira Server info disclosure / SSRF.", severity="medium", cvss=5.3, category="cms", vendor="Atlassian", product="Jira"),
    _c("CVE-2019-11580", "Atlassian Jira Widget SSRF.", severity="critical", cvss=9.8, category="cms", vendor="Atlassian", product="Jira"),
    _c("CVE-2022-0543", "Redis Lua sandbox escape RCE.", severity="critical", cvss=10.0, category="database", vendor="Redis", product="Redis"),
    _c("CVE-2021-32675", "Redis integer overflow DoS.", severity="high", cvss=7.5, category="database", vendor="Redis", product="Redis"),
    _c("CVE-2022-24990", "TOTOLink router command injection.", severity="critical", cvss=9.8, category="iot", vendor="TOTOLink", product="Router"),
    _c("CVE-2021-45382", "TOTOLink multiple products RCE.", severity="critical", cvss=9.8, category="iot", vendor="TOTOLink", product="Router"),
    _c("CVE-2018-10561", "Dasan GPON router auth bypass.", severity="critical", cvss=9.8, category="iot", vendor="Dasan", product="GPON"),
    _c("CVE-2020-8958", "WordPress File Manager plugin RCE.", severity="critical", cvss=9.8, category="cms", vendor="WordPress", product="File Manager plugin"),
    _c("CVE-2022-4060", "WordPress WP Fastest Cache RCE.", severity="critical", cvss=9.8, category="cms", vendor="WordPress", product="WP Fastest Cache"),
    _c("CVE-2023-40044", "WinRAR RCE via crafted archive.", severity="high", cvss=7.8, category="file_transfer", vendor="RARLAB", product="WinRAR"),
    _c("CVE-2017-11882", "Microsoft Office EQNEDT32 RCE.", severity="high", cvss=7.8, category="mail", vendor="Microsoft", product="Office"),
    _c("CVE-2021-40444", "Microsoft MSHTML remote code execution.", severity="high", cvss=7.8, category="mail", vendor="Microsoft", product="MSHTML"),
    _c("CVE-2023-36884", "Office/Windows HTML RCE (Storm-0978).", severity="high", cvss=8.3, category="mail", vendor="Microsoft", product="Office"),
    _c("CVE-2020-10199", "Nexus Repository Manager RCE.", severity="high", cvss=8.8, category="web_rce", vendor="Sonatype", product="Nexus"),
    _c("CVE-2020-10204", "Nexus Repository Manager RCE (admin).", severity="high", cvss=8.8, category="web_rce", vendor="Sonatype", product="Nexus"),
    _c("CVE-2019-7238", "Nexus Repository Manager EL injection RCE.", severity="critical", cvss=9.8, category="web_rce", vendor="Sonatype", product="Nexus"),
    _c("CVE-2021-3129", "Laravel Ignition debug mode RCE.", severity="critical", cvss=9.8, category="web_rce", vendor="Laravel", product="Ignition"),
    _c("CVE-2018-15133", "Laravel deserialization RCE.", severity="critical", cvss=9.8, category="web_rce", vendor="Laravel", product="Framework"),
    _c("CVE-2022-26135", "MobileIron / Ivanti MobileIron auth bypass.", severity="critical", cvss=9.8, category="auth_bypass", vendor="Ivanti", product="MobileIron"),
    _c("CVE-2023-35078", "Ivanti EPMM auth bypass.", severity="critical", cvss=9.8, category="auth_bypass", vendor="Ivanti", product="EPMM"),
    _c("CVE-2020-6287", "SAP NetWeaver RECON missing auth RCE.", severity="critical", cvss=10.0, category="web_rce", vendor="SAP", product="NetWeaver"),
    _c("CVE-2022-22536", "SAP NetWeaver request smuggling RCE.", severity="critical", cvss=9.8, category="web_rce", vendor="SAP", product="NetWeaver"),
]

# Backward-compatible export
SEED_CVES = CVE_CATALOG

CVE_CATEGORIES: dict[str, str] = {
    "web_rce": "Web / application RCE",
    "cms": "CMS & plugins",
    "network": "Network services",
    "remote_access": "Remote access (SSH/RDP/VNC)",
    "database": "Databases",
    "cloud": "Cloud & virtualization",
    "iot": "IoT / routers",
    "proxy": "VPN / proxy / WAF",
    "mail": "Mail & collaboration",
    "container": "Containers & orchestration",
    "file_transfer": "FTP / MFT / file share",
    "auth_bypass": "Authentication bypass",
    "other": "Other",
}
