"""Built-in fingerprint rules seeded on first bootstrap."""

from __future__ import annotations

from typing import Any

BUILTIN_RULES: list[dict[str, Any]] = [
    {
        "name": "SSH brute force — repeated auth failures",
        "description": "Detects common SSH login failure bursts in honeypot logs.",
        "pattern": r"(?i)(failed password|authentication failure|invalid user).{0,80}(failed password|authentication failure)",
        "pattern_type": "regex",
        "match_field": "both",
        "attack_type": "brute_force",
        "tool": None,
        "technique": "T1110",
        "cve_ids": [],
        "severity": "medium",
        "priority": 90,
    },
    {
        "name": "SQL injection probe",
        "description": "Classic SQLi patterns in HTTP or command payloads.",
        "pattern": r"(?i)(union\s+select|'?\s*or\s+1\s*=\s*1|sleep\s*\(\s*\d+\s*\)|information_schema)",
        "pattern_type": "regex",
        "match_field": "both",
        "attack_type": "injection",
        "tool": "sqlmap",
        "technique": "T1190",
        "cve_ids": [],
        "severity": "high",
        "priority": 85,
    },
    {
        "name": "Path traversal / LFI",
        "description": "Directory traversal and local file inclusion attempts.",
        "pattern": r"(?i)(\.\./|\.\.\\|/etc/passwd|/proc/self/environ|file:///)",
        "pattern_type": "regex",
        "match_field": "both",
        "attack_type": "path_traversal",
        "tool": None,
        "technique": "T1083",
        "cve_ids": [],
        "severity": "high",
        "priority": 80,
    },
    {
        "name": "Log4Shell JNDI probe",
        "description": "Log4j JNDI lookup injection attempts (CVE-2021-44228 family).",
        "pattern": r"(?i)\$\{jndi:(ldap|dns|rmi|iiop)://",
        "pattern_type": "regex",
        "match_field": "both",
        "attack_type": "rce_probe",
        "tool": None,
        "technique": "T1190",
        "cve_ids": ["CVE-2021-44228", "CVE-2021-45046"],
        "severity": "critical",
        "priority": 100,
    },
    {
        "name": "Web shell upload attempt",
        "description": "Common web shell and PHP backdoor upload patterns.",
        "pattern": r"(?i)(c99shell|r57shell|webshell|eval\s*\(\s*base64_decode|<\?php\s+@eval)",
        "pattern_type": "regex",
        "match_field": "both",
        "attack_type": "webshell",
        "tool": None,
        "technique": "T1505.003",
        "cve_ids": [],
        "severity": "critical",
        "priority": 95,
    },
    {
        "name": "Scanner — nmap",
        "description": "Nmap user-agent or script fingerprint in HTTP logs.",
        "pattern": r"(?i)(nmap|Nmap Scripting Engine|libwww-perl.*nmap)",
        "pattern_type": "regex",
        "match_field": "both",
        "attack_type": "reconnaissance",
        "tool": "nmap",
        "technique": "T1595",
        "cve_ids": [],
        "severity": "low",
        "priority": 60,
    },
    {
        "name": "Scanner — masscan",
        "description": "Masscan or high-volume port scan indicators.",
        "pattern": r"(?i)(masscan|zgrab|httpx|naabu)",
        "pattern_type": "regex",
        "match_field": "both",
        "attack_type": "reconnaissance",
        "tool": "masscan",
        "technique": "T1595",
        "cve_ids": [],
        "severity": "low",
        "priority": 55,
    },
    {
        "name": "Mirai / IoT botnet patterns",
        "description": "Common Mirai-style telnet/IoT exploitation strings.",
        "pattern": r"(?i)(/bin/busybox\s+(?:MIRAI|ECCHI)|/dev/netslink/|shellshock|CVE-2014-6271)",
        "pattern_type": "regex",
        "match_field": "both",
        "attack_type": "botnet",
        "tool": "mirai",
        "technique": "T1584",
        "cve_ids": ["CVE-2014-6271"],
        "severity": "high",
        "priority": 88,
    },
    {
        "name": "Spring4Shell probe",
        "description": "Spring Framework RCE class loader manipulation (CVE-2022-22965).",
        "pattern": r"(?i)(class\.module\.classLoader|springframework|tomcat.*classloader)",
        "pattern_type": "regex",
        "match_field": "both",
        "attack_type": "rce_probe",
        "tool": None,
        "technique": "T1190",
        "cve_ids": ["CVE-2022-22965"],
        "severity": "critical",
        "priority": 92,
    },
    {
        "name": "Reverse shell command",
        "description": "Common bash/nc reverse shell one-liners.",
        "pattern": r"(?i)(/bin/bash\s+-i\s+>&\s*/dev/tcp/|nc\s+-e\s+/bin/(?:ba)?sh|python\s+-c\s+['\"]import\s+socket)",
        "pattern_type": "regex",
        "match_field": "both",
        "attack_type": "reverse_shell",
        "tool": None,
        "technique": "T1059",
        "cve_ids": [],
        "severity": "critical",
        "priority": 98,
    },
    {
        "name": "Confluence OGNL / CVE probe",
        "description": "Confluence exploitation and OGNL injection patterns.",
        "pattern": r"(?i)(CVE-2022-26134|CVE-2023-22515|ognl\.Ognl|getClass\(\)\.forName|confluence.*admin)",
        "pattern_type": "regex",
        "match_field": "both",
        "attack_type": "rce_probe",
        "tool": None,
        "technique": "T1190",
        "cve_ids": ["CVE-2022-26134", "CVE-2023-22515"],
        "severity": "critical",
        "priority": 94,
    },
    {
        "name": "Exchange ProxyLogon indicators",
        "pattern": r"(?i)(CVE-2021-26855|/autodiscover/autodiscover\.json|ProxyLogon|X-BEResource)",
        "pattern_type": "regex",
        "match_field": "both",
        "attack_type": "rce_probe",
        "cve_ids": ["CVE-2021-26855", "CVE-2021-26857"],
        "severity": "critical",
        "priority": 93,
    },
    {
        "name": "Drupalgeddon probe",
        "pattern": r"(?i)(CVE-2018-7600|drupal.*ajax|form_build_id.*#)",
        "pattern_type": "regex",
        "match_field": "both",
        "attack_type": "rce_probe",
        "cve_ids": ["CVE-2018-7600"],
        "severity": "critical",
        "priority": 91,
    },
    {
        "name": "WebLogic T3/IIOP probe",
        "pattern": r"(?i)(CVE-2020-14882|/console/images/%252e%252e|weblogic.*iiop|t3://)",
        "pattern_type": "regex",
        "match_field": "both",
        "attack_type": "rce_probe",
        "cve_ids": ["CVE-2020-14882", "CVE-2017-10271"],
        "severity": "critical",
        "priority": 90,
    },
    {
        "name": "Fortinet / VPN auth bypass probe",
        "pattern": r"(?i)(CVE-2022-40684|CVE-2023-27997|/remote/login|fortigate|global-protect)",
        "pattern_type": "regex",
        "match_field": "both",
        "attack_type": "auth_bypass",
        "cve_ids": ["CVE-2022-40684", "CVE-2023-27997"],
        "severity": "critical",
        "priority": 89,
    },
    {
        "name": "MOVEit transfer probe",
        "pattern": r"(?i)(CVE-2023-34362|moveit.*human\.aspx|Progress MOVEit)",
        "pattern_type": "regex",
        "match_field": "both",
        "attack_type": "rce_probe",
        "cve_ids": ["CVE-2023-34362"],
        "severity": "critical",
        "priority": 88,
    },
    {
        "name": "Citrix ADC / Bleed probe",
        "pattern": r"(?i)(CVE-2019-19781|CVE-2023-4966|/vpn/../vpns/cfg|citrix.*bleed)",
        "pattern_type": "regex",
        "match_field": "both",
        "attack_type": "rce_probe",
        "cve_ids": ["CVE-2019-19781", "CVE-2023-4966"],
        "severity": "critical",
        "priority": 87,
    },
    {
        "name": "SMB EternalBlue probe",
        "pattern": r"(?i)(CVE-2017-0144|MS17-010|EternalBlue|\x00SMB)",
        "pattern_type": "regex",
        "match_field": "both",
        "attack_type": "network_exploit",
        "cve_ids": ["CVE-2017-0144"],
        "severity": "critical",
        "priority": 86,
    },
    {
        "name": "Redis unauthorized command",
        "pattern": r"(?i)(CONFIG\s+SET\s+dir|slaveof\s+|CVE-2022-0543|redis.*unauth)",
        "pattern_type": "regex",
        "match_field": "both",
        "attack_type": "rce_probe",
        "cve_ids": ["CVE-2022-0543"],
        "severity": "critical",
        "priority": 84,
    },
    {
        "name": "Laravel Ignition RCE",
        "pattern": r"(?i)(CVE-2021-3129|_ignition/execute-solution|laravel.*ignition)",
        "pattern_type": "regex",
        "match_field": "both",
        "attack_type": "rce_probe",
        "cve_ids": ["CVE-2021-3129"],
        "severity": "critical",
        "priority": 83,
    },
    {
        "name": "WordPress plugin RCE patterns",
        "pattern": r"(?i)(CVE-2023-6553|CVE-2020-8958|wp-content/plugins/.*\.php\?.*cmd)",
        "pattern_type": "regex",
        "match_field": "both",
        "attack_type": "rce_probe",
        "cve_ids": ["CVE-2023-6553", "CVE-2020-8958"],
        "severity": "high",
        "priority": 82,
    },
    {
        "name": "PAN-OS GlobalProtect probe",
        "pattern": r"(?i)(CVE-2024-3400|global-protect/portal|pan-os.*cmd)",
        "pattern_type": "regex",
        "match_field": "both",
        "attack_type": "rce_probe",
        "cve_ids": ["CVE-2024-3400"],
        "severity": "critical",
        "priority": 96,
    },
    {
        "name": "XXE / XML external entity",
        "pattern": r"(?i)(<!ENTITY\s+\w+\s+SYSTEM|<!DOCTYPE\s+\w+\s*\[.*SYSTEM)",
        "pattern_type": "regex",
        "match_field": "both",
        "attack_type": "injection",
        "technique": "T1190",
        "cve_ids": [],
        "severity": "high",
        "priority": 78,
    },
    {
        "name": "Deserialization gadget probe",
        "pattern": r"(?i)(ysoserial|CommonsCollections|ObjectInputStream|rO0AB)",
        "pattern_type": "regex",
        "match_field": "both",
        "attack_type": "deserialization",
        "tool": "ysoserial",
        "cve_ids": ["CVE-2017-5638"],
        "severity": "critical",
        "priority": 85,
    },
]
